import { defineConfig, lazyPlugins } from "vite-plus";
import { jevApiPlugin } from "./server/jev-api.ts";

/**
 * Varlock resolves TYPESAFE_API_KEY from 1Password, which can wait on a desktop-app
 * prompt. Only the dev and preview servers need the key (the `/api/jev` middleware
 * reads it per request), so the client build, unit tests, and metadata reads (check,
 * lint, fmt) skip the plugin. It loads the env as soon as its module is imported,
 * hence the dynamic import.
 */
export default defineConfig(({ command }) => {
  const servesApi = command === "serve" && !process.env.VITEST;
  return {
    plugins: lazyPlugins(async () => {
      if (!servesApi) return [jevApiPlugin()];
      const { varlockVitePlugin } = await import("@varlock/vite-integration");
      return [varlockVitePlugin(), jevApiPlugin()];
    }),
    staged: {
      "*": "vp check --fix",
    },
    // env.d.ts is regenerated by Varlock on every dev-server start, in its own formatting.
    fmt: { ignorePatterns: ["env.d.ts"] },
    lint: {
      jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
      rules: { "vite-plus/prefer-vite-plus-imports": "error" },
      options: { typeAware: true, typeCheck: true },
    },
  };
});
